- hosts: all
  gather_facts: no
  remote_user: "{{ build_user }}"

  tasks:

  - name: download release
    command: wget -O '/tmp/{{ version }}.zip' 'https://github.com/nens/{{ repo_name }}/releases/download/{{ version }}/{{ version }}.zip'

  - name: rm old frontend
    file: path={{ deploy_path }} state=absent

  - name: mkdir
    file: path={{ deploy_path }} state=directory owner={{ build_user }}

  - name: unzip release
    command: unzip /tmp/{{ version }}.zip -d {{ deploy_path }}

  - name: rm tmp zip
    file: path=/tmp/{{ version}}.zip state=absent
